# https://help.github.com/en/articles/metadata-syntax-for-github-actions

name: 'Pisac'
author: 'Alexandr Chernyaev'
description: 'Keep git commit histories clean.'

branding:
    icon: 'message-square'
    color: 'white'

runs:
  using: "composite"
  steps:
    - name: Setup PHP 🔧
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: mbstring, zip
        coverage: none
        tools: composer:v2

    - name: Install 👀
      run: composer global require "pisac/pisac:0.0.5" --with-all-dependencies

    - name: Execute 🔧
      run: pisac check
